"""add_horizon_to_signals_portfolios

Revision ID: 4946dc52378f
Revises: e818877d88cd
Create Date: 2026-05-18 19:55:52.611791
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



revision: str = '4946dc52378f'
down_revision: Union[str, None] = 'e818877d88cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

horizon_enum = postgresql.ENUM('SHORT', 'MEDIUM', 'LONG', name='horizon')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    horizon_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('portfolio_snapshots', sa.Column('horizon', horizon_enum, server_default='MEDIUM', nullable=False))
    op.add_column('signals', sa.Column('horizon', horizon_enum, server_default='MEDIUM', nullable=False))
    op.alter_column('portfolio_snapshots', 'horizon', server_default=None)
    op.alter_column('signals', 'horizon', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'horizon')
    op.drop_column('portfolio_snapshots', 'horizon')
    horizon_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
