"""add_username_to_users

Revision ID: 9bf33a521c34
Revises: 4946dc52378f
Create Date: 2026-05-19 00:13:14.186725
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9bf33a521c34'
down_revision: Union[str, None] = '4946dc52378f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.execute("UPDATE users SET username = lower(split_part(email, '@', 1)) WHERE username IS NULL")
    op.alter_column('users', 'username', nullable=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
