"""initial_platform_schema

Revision ID: c09049a669f9
Revises: 
Create Date: 2026-05-18 18:58:34.187505
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'c09049a669f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.Enum('DAILY', 'HOURLY', 'FIFTEEN_MIN', name='timeframe'), nullable=False),
    sa.Column('horizon_bars', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.DateTime(), nullable=True),
    sa.Column('train_end', sa.DateTime(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.Enum('DAILY', 'HOURLY', 'FIFTEEN_MIN', name='timeframe'), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_bist100', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_sector'), 'symbols', ['sector'], unique=False)
    op.create_index(op.f('ix_symbols_ticker'), 'symbols', ['ticker'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', 'TRIAL', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_run_id', 'symbol_id', 'prediction_time', name='uq_prediction_run_symbol_time')
    )
    op.create_index('ix_predictions_symbol_time', 'predictions', ['symbol_id', 'prediction_time'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.Enum('DAILY', 'HOURLY', 'FIFTEEN_MIN', name='timeframe'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'timestamp', name='uq_price_bar_symbol_timeframe_ts')
    )
    op.create_index('ix_price_bars_symbol_timeframe_ts', 'price_bars', ['symbol_id', 'timeframe', 'timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('signal_time', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.Enum('DAILY', 'HOURLY', 'FIFTEEN_MIN', name='timeframe'), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', 'HOLD', name='signaldirection'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TARGET_HIT', 'STOP_HIT', 'EXPIRED', 'CANCELLED', name='signalstatus'), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('model_score', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('volume_score', sa.Float(), nullable=False),
    sa.Column('relative_strength_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_date_score', 'signals', ['signal_time', 'final_score'], unique=False)
    op.create_index('ix_signals_symbol_status', 'signals', ['symbol_id', 'status'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('suggested_weight', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_snapshot_id'], ['portfolio_snapshots.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_snapshot_id', 'symbol_id', name='uq_portfolio_item_snapshot_symbol')
    )
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('return_3d', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('return_10d', sa.Float(), nullable=True),
    sa.Column('return_20d', sa.Float(), nullable=True),
    sa.Column('max_gain', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('hit_target', sa.Boolean(), nullable=False),
    sa.Column('hit_stop', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', name='uq_signal_outcome_signal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_outcomes')
    op.drop_table('portfolio_items')
    op.drop_index('ix_signals_symbol_status', table_name='signals')
    op.drop_index('ix_signals_date_score', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_price_bars_symbol_timeframe_ts', table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index('ix_predictions_symbol_time', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symbols_ticker'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_sector'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_table('portfolio_snapshots')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
