"""add_feature_values

Revision ID: e818877d88cd
Revises: c09049a669f9
Create Date: 2026-05-18 19:28:53.638100
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'e818877d88cd'
down_revision: Union[str, None] = 'c09049a669f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

timeframe_enum = postgresql.ENUM('DAILY', 'HOURLY', 'FIFTEEN_MIN', name='timeframe', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', timeframe_enum, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('feature_set', sa.String(length=64), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('volume_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'timestamp', 'feature_set', name='uq_feature_symbol_timeframe_ts_set')
    )
    op.create_index('ix_feature_values_symbol_timeframe_ts', 'feature_values', ['symbol_id', 'timeframe', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_values_symbol_timeframe_ts', table_name='feature_values')
    op.drop_table('feature_values')
    # ### end Alembic commands ###
